Fix dev
sanger-tol/blobtoolkit pull request #35
Opened 2022-11-04 12:00 UTC by zb32

## PR checklist

- [ X ] This comment contains a description of changes (with reason).
   Update module directory structure to match nf-core V2.6 and update documentation. 
- [ X ] Make sure your code lints (`nf-core lint`).
- [X ] Ensure the test suite passes (`nextflow run . -profile test,docker --outdir <OUTDIR>`).
- [X ] Usage Documentation in `docs/usage.md` is updated.
- [ X] `README.md` is updated (including new tool citations and authors/contributors).

2022-12-04 12:06 UTC, priyanka-surana requested changes
Include everything till the BUSCO subworkflow (#36).
1. README.md - Address all TODOs: https://github.com/sanger-tol/readmapping/blob/main/README.md
2. Add docs/parameters.md using `nf-core schema docs --help`: https://github.com/sanger-tol/readmapping/blob/main/docs/parameters.md
3. Add docs/output.md: https://github.com/sanger-tol/insdcdownload/blob/dev/docs/output.md

2022-12-09 08:56 UTC, priyanka-surana requested changes
1. The usage docs refers to `nf-core/blobtoolkit` and that link, please update
2. In general do a search for similar terms/links throughout the pipeline and update.

2022-12-09 08:56 UTC, priyanka-surana commented on README.md
> +On release, tests run the pipeline on a dataset on the Wellcome Sanger Institute HPC farm with Sigularity containers. This ensures that the pipeline runs, has sensible resource allocation defaults se
We do not have a place where the test results can be viewed yet. I think it is best if we delete the last sentence 
> The results obtained from ...

2022-12-09 08:56 UTC, priyanka-surana commented on README.md
>  ## Credits
Need to update credits.
1. Change from `nf-core/blobtoolkit` to `sanger-tol/blobtoolkit`
2. Add your name to the list as well.
3. Give credit to Richard Challis for design/original pipeline and Sujai Kumar for maintaining + Link to the original blobtoolkit
4. Add Matthieu and me
5. Also add a sentence on how Alexander was supported by GSoC
6. Remove TODO

2023-01-05 10:43 UTC, gq1 commented on .github/workflows/ci.yml
> +          - "latest-everything"
```suggestion
          - ""
```

2023-01-06 11:33 UTC, priyanka-surana requested changes
Small changes. Mostly looks good 👍

2023-01-06 11:33 UTC, priyanka-surana commented on .github/workflows/ci.yml
> +          - "21.10.3"
I would update this to `22.10.1` at least, but stick to a stable version.
https://github.com/nextflow-io/nextflow/releases

2023-01-06 11:33 UTC, priyanka-surana commented on README.md
Either remove Slack, Twitter and YouTube or update it to the correct links. It is all pointing to `nf-core` at this point.

2023-01-06 11:33 UTC, priyanka-surana commented on assets/email_template.txt
>    nf-core/blobtoolkit v${version}
This should be `sanger-tol`

2023-01-06 11:33 UTC, priyanka-surana commented on conf/modules.config
> +    }
Was this not in your original `mosdepth` PR?

2023-01-06 11:33 UTC, priyanka-surana commented on docs/usage.md
>  ```
No spaces in comma separated files. This will cause errors in processing.

2023-01-06 11:33 UTC, priyanka-surana commented on docs/usage.md
>  ```
Same here. No spaces please. During processing, spaces will get read as part of the file name or data type and cause errors. Does the test samplesheet have spaces?

2023-01-11 10:26 UTC, priyanka-surana approved these changes
I think this is all good. I would recommend adding your name as the author as well in `nextflow.config`. Let's get one more approval before we merge.

2023-01-11 10:40 UTC, priyanka-surana commented on nextflow.config
> +    author          = 'Alexander Ramos and Zaynab Butt'
```suggestion
    author          = 'Alexander Ramos, Zaynab Butt'
```

2023-01-11 10:58 UTC, merged